<!DOCTYPE html>
<html lang="bn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $article->title }}</title>
    <style>
            @font-face {
            font-family: 'SolaimanLipi';
            src: url("{{ storage_path('fonts/SolaimanLipi.ttf') }}") format('truetype');
            font-weight: normal;
            font-style: normal;
        }

        body {
            font-family: 'SolaimanLipi', sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            font-size: 24px;
            margin-bottom: 10px;
        }
        .meta {
            text-align: center;
            font-size: 14px;
            color: #555;
        }
        .content {
            margin-top: 20px;
            text-align: justify;
        }
        .image-container {
            text-align: center;
            margin: 20px 0;
        }
        .image-container img {
            max-width: 100%;
            height: auto;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #777;
        }
        h1, h2, h3 {
        font-family: 'SolaimanLipi', sans-serif !important;
    }
    </style>
</head>
<body>

    <div class="header">
        <h1>{{ $article->title }}</h1>
        <p class="meta">Published on {{ $article->created_at->format('d M, Y') }} | Category: {{ $article->category->name }}</p>
    </div>

    @if($article->image)
    <div class="image-container">
        <img src="{{ public_path('storage/'.$article->image) }}" alt="Article Image">
    </div>
    @endif

    <div class="content">
        <p>{!! nl2br($article->content) !!}</p>
    </div>

    <div class="footer">
        <p>Generated by News Portal - {{ now()->format('d M, Y') }}</p>
    </div>

</body>
</html>
